within IDEAS.Fluid.PvtCollectors.Validation.PVT1.BaseClasses;
model PartialPvtCollectorValidationPVT1
  "Extended partial solar (thermal) collector with discretized PV electrical calculations"
  extends IDEAS.Fluid.SolarCollectors.BaseClasses.PartialSolarCollector(
      redeclare IDEAS.Fluid.PvtCollectors.Data.GenericQuasiDynamic per,
                                                                        break
      weaBus,
    break HDifTilIso,
    break HDirTil);

  // ===== Photovoltaic Parameters =====
  final parameter Modelica.Units.SI.Irradiance Gstc = 1000
    "Irradiance at Standard Conditions (W/m2)";
  parameter Modelica.Units.SI.Efficiency   pLossFactor = 0.10
    "Loss factor of the PV panel(s)" annotation(Dialog(group="Electrical parameters"));
  constant Modelica.Units.SI.Temperature _T_ref = 25 + 273
    "Reference cell temperature (K)";
  parameter IDEAS.Fluid.PvtCollectors.Types.CollectorType collectorType =
  IDEAS.Fluid.PvtCollectors.Types.CollectorType.Uncovered
    "Type of collector (used to select (tau*alpha)_eff)";
protected
  final parameter Real tauAlphaEff =
    if collectorType == IDEAS.Fluid.PvtCollectors.Types.CollectorType.Uncovered then 0.901 else 0.84
    "Effective transmittance–absorptance product";
  final parameter Modelica.Units.SI.CoefficientOfHeatTransfer UAbsFluid =
  ((tauAlphaEff - per.eta0El) * (per.c1 + abs(per.gamma)*Gstc))
  / ((tauAlphaEff - per.eta0El) - per.eta0)
  "Heat transfer coefficient calculated from EN12975 parameters";

  // ===== Measurement Data =====
  // (Assumes that an outer measurement is available providing measurement data)

  // ===== Variables for PV Electrical Calculations per Segment =====
  // (Assuming that the base model provides arrays: temSen, QGai, QLos, and the scalar ATot_internal)
  Real Tm[nSeg]         "Mean fluid temperature for each segment";
  Real temCell[nSeg]     "Cell temperature for each segment (K)";
  Real temDiff[nSeg]     "Temperature difference of the cell relative to reference (K)";
  Real G                "Global irradiance on the panel (W/m2)";
  Real qth[nSeg]        "Thermal power density per segment [W/m2]";

  // ===== Real Output Connectors =====
public
  outer Modelica.Blocks.Sources.CombiTimeTable meaDat(
    tableOnFile=true,
    tableName="data",
    fileName=Modelica.Utilities.Files.loadResource("modelica://PvtMod/Resources/Validation/MeasurementData/Typ1_modelica.txt"),
    columns=1:25)                                     annotation (Placement(transformation(extent={{26,68},
            {6,88}})));
protected
  Modelica.Blocks.Interfaces.RealOutput pelOut
    "Electrical power generated by the photovoltaic installation"
    annotation(Placement(transformation(extent={{100,-70},{120,-50}})));
  Modelica.Blocks.Interfaces.RealOutput qThOut
    "Total thermal power generated by the PVT installation"
    annotation(Placement(transformation(extent={{100,-90},{120,-70}})));
  Modelica.Blocks.Interfaces.RealOutput temModOut(
  quantity="Temperature",
    unit="K",
    displayUnit="degC")
    "Average cell temperature"
    annotation(Placement(transformation(extent={{100,58},{120,78}})));
  Modelica.Blocks.Interfaces.RealOutput temMeaOut(
  quantity="Temperature",
    unit="K",
    displayUnit="degC")
    "Average fluid temperature"
    annotation(Placement(transformation(extent={{100,78},{120,98}})));
   Modelica.Blocks.Interfaces.RealOutput solarPowerInternal[nSeg]
  "Electrical power produced by each discretized PV segment (W)";
equation
  // Directly calculate global irradiance from measurement data
  G =meaDat.y[2];

  // Calculate PV electrical performance for each segment
  for i in 1:nSeg loop
    // Retrieve the mean fluid temperature from the sensor array (provided by the base model)
    Tm[i] = temSen[i].T;
    // Compute the local thermal power density (W/m2)
    qth[i] = (QGai[i].Q_flow + QLos[i].Q_flow) / (ATot_internal/nSeg);
    // Estimate the cell temperature using fluid temperature and thermal flux
    temCell[i] = Tm[i] + qth[i] / UAbsFluid;
    // Determine the temperature difference relative to the reference temperature
    temDiff[i] = temCell[i] - _T_ref;
    // Calculate electrical power output per segment using the PV performance equation
    solarPowerInternal[i] = (ATot_internal/nSeg) * (per.Pstc/per.A) * (G/Gstc) *
                         (1 + per.gamma*temDiff[i]) * (1 - pLossFactor);

  end for;

  // Assign the sum of the segment electrical outputs to the output connector pel
  pelOut = sum(solarPowerInternal);

  // Calculate the total thermal power by multiplying the thermal density with the segment area and summing up
  qThOut = (ATot_internal/nSeg) * sum(qth);

  // Calculate the average cell temperature, defined as module temperature
  temModOut = sum(temCell)/nSeg;

  // Calculate the average fluid temperature, defined as module temperature
  temMeaOut = sum(Tm)/nSeg;

end PartialPvtCollectorValidationPVT1;
